libdwfl: Fix debuginfod_client redefinition
clang complains:

    In file included from debuginfod-client.c:38:
    ./../debuginfod/debuginfod.h:47:34: error: redefinition of typedef 'debuginfod_client' is a C11 feature [-Werror,-Wtypedef-redefinition]
    typedef struct debuginfod_client debuginfod_client;
                                     ^
    ./libdwfl.h:53:34: note: previous definition is here
    typedef struct debuginfod_client debuginfod_client;
                                     ^

config/eu.am specifies -std=gnu99, and upgrading just for this is an
overkill. So is #including "debuginfod.h", since we don't know if users
even have it. So fix by using "struct debuginfod_client" instead. This
may break the clients that use dwfl_get_debuginfod_client() without
#including "debuginfod.h", but such cases should be rare.

Signed-off-by: Ilya Leoshkevich <iii@linux.ibm.com>